INSERT INTO Cars VALUES('BMW', '420d', 'Dark blue', 'Heads-up display', 500000)
INSERT INTO Cars VALUES('BMW', '320d', 'Black', 'Heads-up display', 400000)
INSERT INTO Cars VALUES('Mercedes', 'AMG', 'Grey', 'Auto pilot', 550000)
INSERT INTO Cars VALUES('Mercedes', 'AMG', 'Dark blue', 'Heads-up display', 600000)
INSERT INTO Cars VALUES('Mercedes', 'AMG', 'White', 'Heads-up display', 300000)
INSERT INTO Cars VALUES('Mercedes', 'AMG', 'Blue', 'Heads-up display', 499500)
INSERT INTO Cars VALUES('Mazda', '6', 'Red', 'Auto pilot', 325000)
INSERT INTO Cars VALUES('Mazda', '6', 'Black', 'Heads-up display', 430000)
INSERT INTO Cars VALUES('Mazda', '6', 'Green', 'Seat warmer', 375000)
INSERT INTO Cars VALUES('Mazda', '3', 'Blue', 'Heads-up display', 63000)